### ISSUE TITLE
Unable to read file from windows

### ISSUE THREAD

**Issue by velteyn** [godotengine/godot-vscode-plugin#232]
Hello I have this error:

`Unable to open 'hterrain_brush.gd': Unable to read file '\\D:\Projects\RedPlanet\addons\zylann.hterrain\hterrain_brush.gd' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat '\\D:\Projects\RedPlanet\addons\zylann.hterrain\hterrain_brush.gd').`

When I open a plugin code and I do CTRL + SPACE over a function on the same file I obain the above error .
I think that in windows \\D:\ is not correctly formatted

**Comment by linkpy** [comment]
Hello.

Could you please give a screenshot of that error ? I can't reproduce as I'm not on Windows so I need more information to investigate the issue.

Thanks

**Comment by Razzlegames** [comment]
Providing screenshots.  Note `Signals` singleton isn't accessible using "go to definition"

![image](https://user-images.githubusercontent.com/8754559/101262695-cd10fb00-36fd-11eb-8f70-db747c23fdcb.png)


The file exists, at the path noted in the error.

![image](https://user-images.githubusercontent.com/8754559/101262786-54f70500-36fe-11eb-8364-a24b3ad303cc.png)

  Note one oddity that you may not be expecting, The Godot project is a subfolder in the `workspace` (due to asset creation files happening outer folders, and not wanting to pollute the Gamedev paths with this).

**Comment by Razzlegames** [comment]
Issue still exists in version `v1.3.1`

**Comment by DaelonSuzuka** [comment]
I think this was an issue with invalid file URIs being sent from the language server, which has since been fixed.
