### ISSUE TITLE
Missing autocompletion for nodes declared as properties

### ISSUE THREAD

**Issue by nanoblit** [godotengine/godot-vscode-plugin#235]
Hello. I can't get autocompletion to work correctly. Here's the code:

```
extends Node2D

onready var sprite: Sprite = $Sprite

func _on_Timer_timeout() -> void:
    sprite.visible = !sprite.visible
```
Written like this "sprite." won't autocomplete the "visible" property, but when I write it like this:

```
func _on_Timer_timeout() -> void:
    var sprite: Sprite = $Sprite
    sprite.visible = !sprite.visible
```
It does autocomplete.
Am I doing something wrong?

**Comment by Razoric480** [comment]
I am unable to recreate the issue on this end. You're not doing anything wrong that I can see, either.

**Comment by linkpy** [comment]
I can recreate the issue on my hand, but only if `Sprite` isn't a node available in the current scene.
If the node is present i have the correct autocompletion.

Looking at the message sent by the LSP server to the extension, the bug is from the LSP itself and not from the extension as the autocomplete suggestions doesn't include any members from the Sprite class.
Opened https://github.com/godotengine/godot/issues/43136 for fixing this bug on the LSP server.

**Comment by Calinou** [comment]
Closing per @linkpy's comment.
