### ISSUE TITLE
"godot-tools.check_status" inconsistency in package.json

### ISSUE THREAD

**Issue by pcting** [godotengine/godot-vscode-plugin#240]
"godot-tools.check_status" should be "godot_tools.check_status"
https://github.com/godotengine/godot-vscode-plugin/blob/60cb0c57fcbafe37f6389d9b3df157c95943e8f3/package.json#L117

**Comment by linkpy** [comment]
That option wasn't used at all before, as in, it has no impact and wasn't even looked for before.
I don't know what is its initial intended behaviour. I think it's just to hide the indicator at the bottom right of the editor, since disabling the status check is not possible.

If you know the original intent of that option please let me know. In the mean time i opened a PR to remove that option.

**Comment by pcting** [comment]
I'd remove it then; I only noticed the inconsistency when I was working on my other PR
