### ISSUE TITLE
Mark "sync" keyword as deprecated

### ISSUE THREAD

**Issue by AaronRecord** [godotengine/godot-vscode-plugin#255]
According to the [godot docs](https://docs.godotengine.org/en/stable/classes/class_multiplayerapi.html), the keyword `sync` is deprecated and `remotesync` should be used instead, but no deprecated keyword warnings occur, like they would if you use `slave` instead of `puppet`.

**Comment by atirut-w** [comment]
I think this should be a Godot language server thing, and the language server is on the engine side.

**Comment by Calinou** [comment]
Does anyone know the syntax for marking keywords as deprecated in TextMate bundle files (`.tmlanguage`)?

**Comment by atirut-w** [comment]
> This should be preferred to removing the keyword from syntax highlighting entirely.

Looking back on this, I don't think language keywords should be deprecated, as in "be usable but regarded as obsolete and best avoided, typically due to having been superseded".

Personally, I think changes to the GDScript should be in a separate "version" of GDScript, and that only functions should be deprecated like in C, C++, C#, Python and many other languages, but that's for another time.

**Comment by Calinou** [comment]
> Looking back on this, I don't think language keywords should be deprecated, as in "be usable but regarded as obsolete and best avoided, typically due to having been superseded".

The keyword has already been deprecated and will be removed in 4.0 (it's already gone from `master`).

**Comment by atirut-w** [comment]
> GDScript is too tightly integrated to Godot for it to be dissociated in a meaningful way.

Doing so will be a huge service to programmers that want "GDScript 2.0" or "Old GDScript" grammars in 4.0, though.

**Comment by DaelonSuzuka** [comment]
We're probably not going to do this because there are perfectly valid reasons to be using an old version of Godot where currently deprecated keywords are still valid.
