### ISSUE TITLE
Relative path for get_node is wrong

### ISSUE THREAD

**Issue by codecat** [godotengine/godot-vscode-plugin#291]
My hierarchy looks like this:
![image](https://user-images.githubusercontent.com/136534/128338102-fda3888b-dfc8-47b5-85bb-86ec841816ef.png)

In the script on the `UI` node, I have the following code:
```gdscript
var p = get_node("../Player")
```

Which works, but the type of `p` is not known by the extension unless I do this:
```gdscript
var p = get_node("Player")
```

In which case, `p` is always null because `get_node` gets its relative path from inside of the node that the script is on.

I have not been using Godot for very long, so I might be misunderstanding some concepts, but I have a suspicion that this is a bug.

Although perhaps the extension is unaware of context in this case and it might not even be possible (or make sense) to fix this?

**Comment by Calinou** [comment]
This may be a bug in the LSP server rather than in the client (this extension), I'm not sure.

cc @Razoric480

**Comment by Razoric480** [comment]
The extension can only send the data it gets back to the LSP, which would have to report back with type information after parsing the scene file. It appears that the LSP is parsing solely from the root of the scene, rather than the node that's doing the call to `get_node`/`$`.

I'll open an issue pointing to the specific problem area over in godotengine/godot.
