### ISSUE TITLE
Syntax highlighting problems

### ISSUE THREAD

**Issue by bend-n** [godotengine/godot-vscode-plugin#355]
### Godot version

3.4

### VS Code version

1.66.2

### Godot Tools VS Code extension version

1.2.0

### System information

ArchLinux x11 

### Issue description

This code: 
```swift
func syntax() -> bool:
	print("hello world")
	return false
```
produces this.
![image](https://user-images.githubusercontent.com/70787919/166173344-58584746-e661-4568-90cb-477ad904bd4e.png)
This code: 
```swift
signal test(argument)

func _ready():
	pass
``` 
produces this. 
![image](https://user-images.githubusercontent.com/70787919/166173403-4e43238d-d19c-4931-a66e-2ba88f2b4d44.png)
This code:
```swift
func directory_view(path = "res://"):
	print(path)
```
produces this.
![image](https://user-images.githubusercontent.com/70787919/166173552-d42418ff-eeb3-48e1-9668-ec0a87c7034b.png)
These issues occur on any color theme.

### Steps to reproduce

- Copy paste code into vscode
- observe

**Comment by atirut-w** [comment]
How does this look with the default theme?

**Comment by Calinou** [comment]
I second what @atirut-w said. When posting syntax highlighting bugs, *always* use the default Dark+ or Light+ themes on screenshots. This rules out any issues specific to the VS Code theme you're currently using.

**Comment by DaelonSuzuka** [comment]
<details>
<summary>Screenshots</summary>

v1.2.0
![Code_sPWjLSeajr](https://user-images.githubusercontent.com/18042232/166265546-2524cb19-cd29-45c4-9234-f60199c5e774.png)

latest dev version
![Code_9OAXrNI9Ga](https://user-images.githubusercontent.com/18042232/166265911-6a6f06c2-51f4-47d6-ac50-63542768c7ef.png)


</details>

I can't reproduce this at all. 

@bend-n if let me know what theme you're using, I can investigate specific incompatibilities. It would also be useful for you to take your screenshots again using the default Dark+ theme, because that would help rule out any issues related to your operating system (which I will not be able to replicate).

**Comment by bend-n** [comment]
@DaelonSuzuka  
![image](https://user-images.githubusercontent.com/70787919/166390171-08c66b90-6956-4bf8-84b6-32b5014b14ae.png)

**Comment by bend-n** [comment]
switching to latest fixed it for me

**Comment by Calinou** [comment]
I'll look into tagging 1.3.0 this week to make the fix widely available :slightly_smiling_face:

**Comment by Calinou** [comment]
1.3.0 is out: https://github.com/godotengine/godot-vscode-plugin/releases/tag/1.3.0
