### ISSUE TITLE
Open with Godot editor command should use the Godot path from user settings

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot-vscode-plugin#420]
### Godot version

N/A

### VS Code version

1.71.0

### Godot Tools VS Code extension version

1.3.1

### System information

N/A

### Problem statement

The command to open current workspace with Godot editor exclusively uses workspace settings and opens a file picker for the editor path without any context if it's not set. This is wrong on so many levels. Even if you set the editor path in user settings, the command does not make use of that.

![What the hell am I supposed to open?](https://user-images.githubusercontent.com/25323231/189265543-6bac9421-d7b6-45b9-9b89-eb352a4a75ed.png)

### Proposed solution

- Check user settings first. If it's not set, check the workspace settings
- If it's not set either, try "godot" just like the debugger
- If everything fails, complain and let the user set the path in their user settings, not open up a file picker.

**Comment by Calinou** [comment]
> If everything fails, complain and let the user set the path in their user settings, not open up a file picker.

I don't see what's wrong with the file picker approach. It requires fewer clicks to configure the extension.

Maybe it should display a second error dialog though, such as "Could not find Godot executable. Do you want to specify the path to a Godot executable on the filesystem?"

**Comment by atirut-w** [comment]
> If we can't change the file dialog's window title, maybe it should display a second error dialog, such as "Could not find Godot executable. Do you want to specify the path to a Godot executable on the filesystem?".

It's not consistent with the debugger's approach though?

**Comment by lbrande** [comment]
I have the exact same problem, also it doesn't remember the selection when you restart the editor even if it's still set in workspace settings.

**Comment by terrehbyte** [comment]
I'm currently running a build based off of `master` at 6a9f408d4eaec1f2da346e50fcabf28435fe7bc5 and I'm no longer able to reproduce the original issue. It behaves as expected: user settings will apply unless superseded by workspace settings.

Considering the question of "What happens if it isn't set?" is harder for me and involves a lot of questions around how automatic we want things to be and how safe that automatic behavior is. As a quick test, I tried to launch a Godot project via CLI (with `-e --project`) with a newer engine version than was used to author the project. The Project Manager will warn you and prompt you to confirm the upgrade, but the CLI does not, so I'm hesitant to endorse it.

**Comment by lalomartins** [comment]
I can confirm it uses the user setting now.

**Comment by DaelonSuzuka** [comment]
I'm reasonably certain that original issue has been resolved here.

@atirut-w Please reopen if you're still experiencing this.
