### ISSUE TITLE
Add a signal icon to the gutter

### ISSUE THREAD

**Issue by ricemashi** [godotengine/godot-vscode-plugin#440]
### Godot version

3.3 Stable

### VS Code version

1.74.1

### Godot Tools VS Code extension version

1.31

### System information

Windows 10

### Problem statement

I am making an action platformer game which requires lots of signals. I cannot differentiate which one is a signal or an original function

### Proposed solution

A signal logo (which is similar to the default godot ide) in the vscode plugin would be quite helpful.

We can implement it like some sort of breakpoint in the line where the signal function prevails.

**Comment by Calinou** [comment]
> I am making an action platformer game which requires lots of signals. I cannot differentiate which one is a signal or an original function

Can you post some example code where this is an issue?

**Comment by ricemashi** [comment]
![image](https://user-images.githubusercontent.com/116453651/208755985-02d9ab2e-9bff-4085-96f0-03111a998c9b.png)

**Comment by DaelonSuzuka** [comment]
Minor nitpick: This screenshot doesn't have signals in it. It has a set of functions, which I'm guessing have signals connected to them in the editor.

I'm going to assume that your request is for an indicator on functions that have signals connected to them. 

I understand why you might want that, but unfortunately, this feature would be prohibitively difficult to implement for rather marginal benefit. Since one script can be attached to many nodes across many scenes, identifying which functions have signals connected to them would require analyzing every connected signal in every scene in the project to figure out if any of them are connected to functions in the current script. This also wouldn't identify connections that are made in code.

Even if this was practical to do, it wouldn't really outperform what's already in your screenshot. The builtin classes in godot have between "very few" and "zero" functions that start with `_on`, so when I look at this, I see a bunch of functions that are supposed to get signals connected to them. I'm not sure what a little icon would tell me that the function names don't.

**Comment by ricemashi** [comment]
I may not understand the way this extension runs under the hood, but what you've just said may be correct. I agree with how little to no benefit this icon feature has but it would be a good friendly way to show signals in vscode. 

Thanks for your reply and explanation.
