### ISSUE TITLE
Comments get hover documentation

### ISSUE THREAD

**Issue by moritz-t-w** [godotengine/godot-vscode-plugin#534]
### Godot version

 v4.1.3.stable.arch_linux

### VS Code version

1.84.2

### Godot Tools VS Code extension version

1.3.1

### System information

Arch Linux

### Issue description

![image](https://github.com/godotengine/godot-vscode-plugin/assets/90388353/e461f77c-3945-4e8f-8a9c-10591c62e5f2)

### Steps to reproduce

Hover over a comment

**Comment by DaelonSuzuka** [comment]
A lot of comments include examples or snippets of usage code, so this is useful behavior in those instances.

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/7b0b3543-a31d-4941-94fa-2b122cae735c)

It _is_ unfortunate that the Language Server isn't correctly resolving the class of the current file when providing hovers. The correct behavior in the situation you posted would be for it recognize that `EnumLabel.gd` is not a `SegmentShape2D` or a `Color`, and thus `a` doesn't refer to a known symbol symbol right now.

I also couldn't change this behavior even if I wanted to, because hovers are provided by the engine itself, using its Language Server. This extension just displays what it gets sent.

**Comment by moritz-t-w** [comment]
Hmm yeah it kinda sucks that there's no formatting in comments to explicitly tell the language server that this is a code snippet. Oh well

**Comment by atirut-w** [comment]
@DaelonSuzuka if you don't mind, do you know anyone familiar with Godot's LSP codes? Just in case.

**Comment by DaelonSuzuka** [comment]
Why does it matter?

**Comment by atirut-w** [comment]
Find, then. I'll study it myself during free time.
