### ISSUE TITLE
match always highlighted red

### ISSUE THREAD

**Issue by moritz-t-w** [godotengine/godot-vscode-plugin#538]
### Godot version

v4.1.3.stable.arch_linux

### VS Code version

1.84.2

### Godot Tools VS Code extension version

1.3.1

### System information

Arch Linux

### Issue description

![image](https://github.com/godotengine/godot-vscode-plugin/assets/90388353/14659bf7-2144-4a23-abf3-d79cf4bdd8f4)
`match` is always treated as tho it was a keyword even when it's used as a variable name, even when spelled with a different case.

### Steps to reproduce

1. type `var match`

**Comment by moritz-t-w** [comment]
Guess this is also a language server issue

**Comment by DaelonSuzuka** [comment]
Interesting. I'm a little surprised that `match` is a valid identifier.

Here's how it look in `master`:

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/4003b172-137f-45bd-b2ec-4accefc5853c)

The variable declaration is correct now, but usage as a variable name is still being highlighted as a keyword. This should be fixed in the next release.

> Guess this is also a language server issue

No, all the highlighting is provided by the extension.

**Comment by moritz-t-w** [comment]
I didn't know `match` was a thing but turns out it's like switch case

**Comment by DaelonSuzuka** [comment]
I spent a couple minutes looking at the syntax highlighting for this and discovered that match _is not_ a valid identifier in the general case. I believe that it's being incorrectly allowed sometimes, and you just got lucky.

I must advise you to not use `match` as a variable name.

![Code_zvjJCIZZfa](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/45dbf1c5-89a1-4ebb-94f9-8068060bdfcc)

![Code_lVwHpqSijF](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/c725c62b-cb27-49d2-aac1-edb1bcaabbe6)

**Comment by moritz-t-w** [comment]
oh that's good to know then :) thanks!
