### ISSUE TITLE
Duplicate var names spam

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot-vscode-plugin#67]
Not sure if this can be tackled on the add-on level, but I find it cumbersome that var's that share their name across .gd files are all displayed separately, causing this kind of spam:

![shot_180608_154241](https://user-images.githubusercontent.com/7307968/41161260-8f5888c6-6b32-11e8-9d18-1419bac736c6.png)

**Comment by Geequlim** [comment]
The new version fixed the problem and will be published when godot 3.2 RC release.
This feature may be turn off if you disable `smart resolve mode` in the godot edtitor settings.

**Comment by Geequlim** [comment]
I'm closing this as the new version has fixed this issue.
You can try the new version of the plugin with godot 3.2 from the [release page](https://github.com/godotengine/godot-vscode-plugin/releases)

Note: In new version this still here if you enabled the `Smart Resolve Mode`. It is a feature instead of bug
