### ISSUE TITLE
No way to run Godot EditorScripts (or "Tools") from VS Code

### ISSUE THREAD

**Issue by blazkowolf** [godotengine/godot-vscode-plugin#93]
In the Godot built-in script editor, you can opt to "run" an `EditorScript` with the `tool` declaration at the top of the script file, however, when a user edits .gd files from VS Code, there is no VS Code-native way of running an `EditorScript`. More specifically, this is not the same as running a current scene. Rather, this is a different kind of script.

**Comment by Geequlim** [comment]
The GDScript can't be run without godot.

**Comment by Razoric480** [comment]
Setting Godot to use an external editor like VScode for convenience makes it impossible to run scripts that derive `EditorScript` through `file->run`, because we can't access the script editor.

Having a way to run an EditorScript from VScode would solve that issue, but there is currently no way to actually talk to the godot editor from the language server.

**Comment by zaha** [comment]
To use EditorScripts it's either necessary to run them via VS Code or enable to use the internal script editor concurrently, as requested in #5759. I'm fine with either solution, but it would be very much appreciated if one of those 2 proposals could be implemented.

Of course, a temporary workaround is to disable the external editor in the editor settings and run the script via the internal script editor, but this get's tedious pretty fast.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/39842 (and/or https://github.com/godotengine/godot-proposals/issues/5759), as this isn't an issue specific to this extension.
